export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_LOADING = 'GET_TOKEN_LOADING';
export const GET_TOKEN_FAILED = 'GET_TOKEN_FAILED';
export const GET_STATE_STORE = 'GET_STATE_STORE';
export const GET_API_TRIVIA = 'GET_API_TRIVIA';
export const CHANGE_INDEX = 'CHANGE_INDEX';
export const CHANGE_CURRENT_QUESTION = 'CHANGE_CURRENT_QUESTION';
